In [68]:
import numpy as np
from sklearn.datasets import load_diabetes
import pandas as pd

In [69]:

x,y = load_diabetes(return_X_y=True)

In [70]:
x

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]], shape=(442, 10))

In [71]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [72]:
x.shape

(442, 10)

In [73]:
y.shape

(442,)

In [74]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [75]:
x_train.shape

(353, 10)

In [76]:
x_test.shape

(89, 10)

In [77]:
from sklearn.linear_model import LinearRegression

In [78]:
lr = LinearRegression()

In [79]:
lr.fit(x_train,y_train)

LinearRegression()

In [80]:
y_pred=lr.predict(x_test)

In [81]:
y_pred

array([139.5475584 , 179.51720835, 134.03875572, 291.41702925,
       123.78965872,  92.1723465 , 258.23238899, 181.33732057,
        90.22411311, 108.63375858,  94.13865744, 168.43486358,
        53.5047888 , 206.63081659, 100.12925869, 130.66657085,
       219.53071499, 250.7803234 , 196.3688346 , 218.57511815,
       207.35050182,  88.48340941,  70.43285917, 188.95914235,
       154.8868162 , 159.36170122, 188.31263363, 180.39094033,
        47.99046561, 108.97453871, 174.77897633,  86.36406656,
       132.95761215, 184.53819483, 173.83220911, 190.35858492,
       124.4156176 , 119.65110656, 147.95168682,  59.05405241,
        71.62331856, 107.68284704, 165.45365458, 155.00975931,
       171.04799096,  61.45761356,  71.66672581, 114.96732206,
        51.57975523, 167.57599528, 152.52291955,  62.95568515,
       103.49741722, 109.20751489, 175.64118426, 154.60296242,
        94.41704366, 210.74209145, 120.2566205 ,  77.61585399,
       187.93203995, 206.49337474, 140.63167076, 105.59

In [82]:
from sklearn.metrics import r2_score

In [83]:
r2_score(y_test,y_pred)

0.4526027629719195

Multiple Linear regression

In [84]:
from sklearn.datasets import make_regression
import plotly.express as px
import plotly.graph_objects as go
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
import plotly.io as pio

In [85]:
x,y=make_regression(n_samples=100,n_features=2,n_informative=2,n_targets=1,noise=50)

In [86]:
x

array([[ 0.31817847, -1.84148185],
       [-0.54911799,  0.00664111],
       [-0.19742343,  0.23747034],
       [ 1.77883769,  0.44456243],
       [ 0.33294818,  0.17029806],
       [ 0.70484868,  0.03800598],
       [-1.29008927, -0.30075593],
       [-0.50365615, -0.34804512],
       [ 0.48874863, -0.27151266],
       [-0.77119911, -1.3180182 ],
       [-2.00930239,  0.34094321],
       [ 0.56298707, -0.8623934 ],
       [ 0.33570761, -0.02468073],
       [ 2.44197982, -1.5658551 ],
       [ 0.3975611 ,  1.33425071],
       [-0.30012443, -2.51507653],
       [ 0.41177473,  1.84997574],
       [-0.3542969 , -0.52119609],
       [-1.0148815 ,  1.49353514],
       [ 1.77562705,  0.07320788],
       [ 0.95985357, -1.57335628],
       [-0.97288114, -1.11382531],
       [-1.03426538,  0.28280652],
       [ 1.17931645,  1.69591677],
       [ 0.43540855,  1.91549812],
       [-0.93968056, -1.4353871 ],
       [-1.39790559, -0.58009297],
       [-0.44189043, -1.0027721 ],
       [-0.76892844,

In [87]:
y.shape

(100,)

In [88]:
x.shape

(100, 2)

In [89]:
df=pd.DataFrame({'Feature1':x[:,0],'Feature2':x[:,1],'target':y })

In [90]:
df.shape

(100, 3)

In [91]:
df.head(5)

Feature1  Feature2      target
0  0.318178 -1.841482   41.582422
1 -0.549118  0.006641   41.681791
2 -0.197423  0.237470    9.118980
3  1.778838  0.444562  160.881713
4  0.332948  0.170298  -50.485918

In [92]:
fig = px.scatter_3d(df, x='Feature1', y='Feature2', z='target')
fig.show()

In [93]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=3)

In [94]:
from sklearn.linear_model import LinearRegression

In [95]:
lr = LinearRegression()

In [96]:
lr.fit(X_train,y_train)

LinearRegression()

In [97]:
y_pred = lr.predict(X_test)


In [98]:
print("MAE",mean_absolute_error(y_test,y_pred))
print("MSE",mean_squared_error(y_test,y_pred))
print("R2 score",r2_score(y_test,y_pred))

MAE 52.1705331251582
MSE 3878.4931071226138
R2 score 0.6111962435028611


NameError: name 'final' is not defined