In [1]:
import numpy as np
from sklearn.datasets import load_diabetes
import pandas as pd

In [2]:

x,y = load_diabetes(return_X_y=True)

In [3]:
x

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]], shape=(442, 10))

In [4]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [5]:
x.shape

(442, 10)

In [6]:
y.shape

(442,)

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [8]:
x_train.shape

(353, 10)

In [9]:
x_test.shape

(89, 10)

In [10]:
from sklearn.linear_model import LinearRegression

In [11]:
lr = LinearRegression()

In [12]:
lr.fit(x_train,y_train)

LinearRegression()

In [13]:
y_pred=lr.predict(x_test)

In [14]:
y_pred

array([139.5475584 , 179.51720835, 134.03875572, 291.41702925,
       123.78965872,  92.1723465 , 258.23238899, 181.33732057,
        90.22411311, 108.63375858,  94.13865744, 168.43486358,
        53.5047888 , 206.63081659, 100.12925869, 130.66657085,
       219.53071499, 250.7803234 , 196.3688346 , 218.57511815,
       207.35050182,  88.48340941,  70.43285917, 188.95914235,
       154.8868162 , 159.36170122, 188.31263363, 180.39094033,
        47.99046561, 108.97453871, 174.77897633,  86.36406656,
       132.95761215, 184.53819483, 173.83220911, 190.35858492,
       124.4156176 , 119.65110656, 147.95168682,  59.05405241,
        71.62331856, 107.68284704, 165.45365458, 155.00975931,
       171.04799096,  61.45761356,  71.66672581, 114.96732206,
        51.57975523, 167.57599528, 152.52291955,  62.95568515,
       103.49741722, 109.20751489, 175.64118426, 154.60296242,
        94.41704366, 210.74209145, 120.2566205 ,  77.61585399,
       187.93203995, 206.49337474, 140.63167076, 105.59

In [15]:
from sklearn.metrics import r2_score

In [16]:
r2_score(y_test,y_pred)

0.4526027629719195

Multiple Linear regression

In [17]:
from sklearn.datasets import make_regression
import plotly.express as px
import plotly.graph_objects as go
from sklearn.metrics import mean_absolute_error,mean_squared_log_error,r2_score
import plotly.io as pio

In [18]:
x,y=make_regression(n_samples=100,n_features=2,n_informative=2,n_targets=1,noise=50)

In [19]:
x

array([[-0.07875922, -0.37282063],
       [-0.75169939,  1.02695383],
       [-1.57322869, -1.13441587],
       [-0.59145027, -1.21076259],
       [-0.44850625,  0.41164342],
       [ 0.23911373, -1.39657716],
       [ 0.37145303, -0.24335361],
       [-0.41826556,  0.84706191],
       [ 0.93531771,  0.57154285],
       [ 0.51014683,  0.42432871],
       [ 1.41357684,  1.1576571 ],
       [-1.80658082, -0.72306005],
       [-0.13519036,  1.26082088],
       [ 0.13108404, -0.41088726],
       [-1.21570862, -0.64657404],
       [-0.04393207, -2.32319291],
       [ 0.33196524,  0.58586986],
       [ 0.12515186, -0.44542644],
       [-1.27859679, -0.54865217],
       [ 2.20872432,  0.62136936],
       [ 1.54702441, -2.09316732],
       [-0.11698156,  1.21942554],
       [-0.32752434, -2.63984543],
       [ 1.27880585,  0.14551763],
       [-0.91501164, -1.3690583 ],
       [-0.40980089, -0.45711165],
       [ 0.05154551, -0.59708029],
       [-0.8173754 ,  1.22132194],
       [ 0.02102191,

In [20]:
y.shape

(100,)

In [21]:
x.shape

(100, 2)

In [22]:
df=pd.DataFrame({'Feature1':x[:,0],'Feature2':x[:,1],'target':y })

In [23]:
df.shape

(100, 3)

In [24]:
df.head(5)

Feature1  Feature2      target
0 -0.078759 -0.372821   21.219017
1 -0.751699  1.026954  105.925496
2 -1.573229 -1.134416 -187.347730
3 -0.591450 -1.210763 -213.511896
4 -0.448506  0.411643   24.873681

In [25]:
fig = px.scatter_3d(df, x='Feature1', y='Feature2', z='target')
fig.show()